services:
  valkey:
    image: valkey/valkey:9-alpine
    ports:
      - '${VALKEY_PORT:-6380}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5

  redis:
    image: redis:8-alpine
    ports:
      - '${REDIS_PORT:-6379}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      start_period: 10s
      retries: 5

  postgres:
    image: postgres:17-alpine
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: neemata
      POSTGRES_PASSWORD: neemata
      POSTGRES_DB: neemata
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'neemata']
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
