packages:
  - packages/*

allowBuilds:
  esbuild: true
  msgpackr-extract: false
  prom-client: true
  protobufjs: true

catalog:
  vite: 8.0.11
  zod: ^4.4.3

minimumReleaseAgeExclude:
  - '@nmtjs/prom-client'
  - '@nmtjs/proxy'
  - '@rolldown/binding-android-arm-eabi@1.2.5'
  - '@rolldown/binding-android-arm64@1.2.5'
  - '@rolldown/binding-darwin-arm64@1.2.5'
  - '@rolldown/binding-darwin-x64@1.2.5'
  - '@rolldown/binding-freebsd-x64@1.2.5'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.5'
  - '@rolldown/binding-linux-arm64-gnu@1.2.5'
  - '@rolldown/binding-linux-arm64-musl@1.2.5'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.5'
  - '@rolldown/binding-linux-s390x-gnu@1.2.5'
  - '@rolldown/binding-linux-x64-gnu@1.2.5'
  - '@rolldown/binding-linux-x64-musl@1.2.5'
  - '@rolldown/binding-openharmony-arm64@1.2.5'
  - '@rolldown/binding-win32-arm64-msvc@1.2.5'
  - '@rolldown/binding-win32-x64-msvc@1.2.5'
  - rolldown@1.2.5
  - '@nmtjs/proxy-darwin-arm64@1.0.0-beta.7'
  - '@nmtjs/proxy-darwin-x64@1.0.0-beta.7'
  - '@nmtjs/proxy-linux-arm-gnueabihf@1.0.0-beta.7'
  - '@nmtjs/proxy-linux-arm64-gnu@1.0.0-beta.7'
  - '@nmtjs/proxy-linux-arm64-musl@1.0.0-beta.7'
  - '@nmtjs/proxy-linux-x64-gnu@1.0.0-beta.7'
  - '@nmtjs/proxy-linux-x64-musl@1.0.0-beta.7'
  - '@rolldown/binding-android-arm-eabi@1.2.6'
  - '@rolldown/binding-android-arm64@1.2.6'
  - '@rolldown/binding-darwin-arm64@1.2.6'
  - '@rolldown/binding-darwin-x64@1.2.6'
  - '@rolldown/binding-freebsd-x64@1.2.6'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.6'
  - '@rolldown/binding-linux-arm64-gnu@1.2.6'
  - '@rolldown/binding-linux-arm64-musl@1.2.6'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.6'
  - '@rolldown/binding-linux-s390x-gnu@1.2.6'
  - '@rolldown/binding-linux-x64-gnu@1.2.6'
  - '@rolldown/binding-linux-x64-musl@1.2.6'
  - '@rolldown/binding-openharmony-arm64@1.2.6'
  - '@rolldown/binding-win32-arm64-msvc@1.2.6'
  - '@rolldown/binding-win32-x64-msvc@1.2.6'
  - rolldown@1.2.6
