packages:
  - packages/*
  - tests
  - playground

catalog:
  zod: ^4.3.5
  vite: 8.0.0-beta.13
  "@nmtjs/proxy": 1.0.0-beta.1

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - prom-client
