# syntax=docker/dockerfile:1.7-labs
FROM node:24-trixie-slim

WORKDIR /workspace

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN corepack enable

COPY --parents ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml ./packages/*/package.json ./tests/*/package.json ./packages/nmtjs/bin ./

RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store pnpm fetch
RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store pnpm install --frozen-lockfile --offline

COPY . .

RUN pnpm build
