export const WORKFLOW_POSTGRES_SCHEMA_VERSION = 1
export const WORKFLOW_POSTGRES_SCHEMA_MANIFEST = {
  version: WORKFLOW_POSTGRES_SCHEMA_VERSION,
  enums: [
    'workflow_run_kind',
    'workflow_node_kind',
    'workflow_node_child_kind',
    'workflow_run_status',
    'workflow_node_status',
    'workflow_attempt_status',
    'workflow_command_kind',
  ],
  enumValues: {
    workflow_run_kind: ['workflow', 'task'],
    workflow_node_kind: [
      'activity',
      'task',
      'workflow',
      'branch',
      'parallel',
      'mapTask',
      'mapWorkflow',
    ],
    workflow_node_child_kind: ['activity', 'task', 'workflow'],
    workflow_run_status: [
      'queued',
      'running',
      'waiting',
      'cancelling',
      'cancelled',
      'failed',
      'completed',
    ],
    workflow_node_status: [
      'pending',
      'running',
      'waiting',
      'cancelling',
      'cancelled',
      'failed',
      'completed',
    ],
    workflow_attempt_status: [
      'started',
      'completed',
      'failed',
      'timedOut',
      'cancelled',
    ],
    workflow_command_kind: ['continue', 'activity', 'task'],
  },
  tables: [
    'workflow_schema_version',
    'workflow_schedules',
    'workflow_runs',
    'workflow_nodes',
    'workflow_attempts',
    'workflow_node_children',
    'workflow_run_leases',
    'workflow_run_events',
    'workflow_commands',
  ],
  constraints: [
    'workflow_schema_version_pkey',
    'workflow_schema_version_singleton_chk',
    'workflow_schedules_pkey',
    'workflow_schedules_name_key',
    'workflow_schedules_cadence_chk',
    'workflow_runs_pkey',
    'workflow_nodes_pkey',
    'workflow_attempts_pkey',
    'workflow_attempts_child_attempt_key',
    'workflow_node_children_pkey',
    'workflow_run_leases_pkey',
    'workflow_run_events_pkey',
    'workflow_commands_pkey',
    'workflow_runs_parent_run_fk',
    'workflow_runs_root_run_fk',
    'workflow_runs_parent_node_fk',
    'workflow_nodes_run_fk',
    'workflow_attempts_node_fk',
    'workflow_node_children_run_fk',
    'workflow_node_children_node_fk',
    'workflow_node_children_child_run_fk',
    'workflow_node_children_current_attempt_fk',
    'workflow_run_leases_run_fk',
    'workflow_run_events_run_fk',
    'workflow_commands_run_fk',
  ],
  indexes: [
    'workflow_runs_idempotency_idx',
    'workflow_schedules_due_idx',
    'workflow_runs_parent_idx',
    'workflow_runs_root_idx',
    'workflow_runs_input_gin_idx',
    'workflow_runs_tags_gin_idx',
    'workflow_attempts_node_idx',
    'workflow_node_children_node_idx',
    'workflow_node_children_child_run_idx',
    'workflow_run_events_run_idx',
    'workflow_run_events_root_idx',
    'workflow_commands_run_idx',
    'workflow_commands_claim_idx',
    'workflow_commands_continue_dedup_idx',
  ],
  constraintDefinitions: {
    workflow_attempts_child_attempt_key: {
      table: 'workflow_attempts',
      type: 'u',
      columns: ['run_id', 'node_name', 'child_key', 'attempt_number'],
    },
    workflow_commands_run_fk: {
      table: 'workflow_commands',
      type: 'f',
      columns: ['run_id'],
    },
    workflow_run_events_run_fk: {
      table: 'workflow_run_events',
      type: 'f',
      columns: ['run_id'],
    },
    workflow_schedules_name_key: {
      table: 'workflow_schedules',
      type: 'u',
      columns: ['name'],
    },
  },
  indexDefinitions: {
    workflow_schedules_due_idx: {
      table: 'workflow_schedules',
      unique: false,
      columns: ['enabled', 'next_run_at'],
    },
    workflow_runs_idempotency_idx: {
      table: 'workflow_runs',
      unique: true,
      columns: ['idempotency_key'],
      predicate: 'idempotency_key IS NOT NULL',
    },
    workflow_runs_parent_idx: {
      table: 'workflow_runs',
      unique: false,
      columns: ['parent_run_id'],
      predicate: 'parent_run_id IS NOT NULL',
    },
    workflow_runs_root_idx: {
      table: 'workflow_runs',
      unique: false,
      columns: ['root_run_id'],
    },
    workflow_runs_input_gin_idx: {
      table: 'workflow_runs',
      unique: false,
      columns: ['input'],
    },
    workflow_runs_tags_gin_idx: {
      table: 'workflow_runs',
      unique: false,
      columns: ['tags'],
    },
    workflow_commands_claim_idx: {
      table: 'workflow_commands',
      unique: false,
      columns: ['kind', 'priority', 'run_at', 'created_at', 'id'],
      directions: ['ASC', 'DESC', 'ASC', 'ASC', 'ASC'],
    },
    workflow_commands_run_idx: {
      table: 'workflow_commands',
      unique: false,
      columns: ['run_id'],
    },
    workflow_commands_continue_dedup_idx: {
      table: 'workflow_commands',
      unique: true,
      columns: ['run_id'],
      predicate:
        "kind = 'continue'::workflow_command_kind AND lease_token IS NULL",
    },
    workflow_attempts_node_idx: {
      table: 'workflow_attempts',
      unique: false,
      columns: ['run_id', 'node_name'],
    },
    workflow_node_children_node_idx: {
      table: 'workflow_node_children',
      unique: false,
      columns: ['run_id', 'node_name'],
    },
    workflow_node_children_child_run_idx: {
      table: 'workflow_node_children',
      unique: false,
      columns: ['child_run_id'],
    },
    workflow_run_events_run_idx: {
      table: 'workflow_run_events',
      unique: false,
      columns: ['run_id', 'id'],
    },
    workflow_run_events_root_idx: {
      table: 'workflow_run_events',
      unique: false,
      columns: ['root_run_id', 'id'],
    },
  },
  columns: {
    workflow_schema_version: {
      id: { type: 'int4', nullable: false },
      version: { type: 'int4', nullable: false },
      installed_at: { type: 'timestamptz', nullable: false },
    },
    workflow_schedules: {
      id: { type: 'uuid', nullable: false },
      name: { type: 'text', nullable: false },
      runnable_kind: { type: 'workflow_run_kind', nullable: false },
      runnable_name: { type: 'text', nullable: false },
      input: { type: 'jsonb', nullable: false },
      tags: { type: 'jsonb', nullable: false },
      cron: { type: 'text', nullable: true },
      every_ms: { type: 'int8', nullable: true },
      enabled: { type: 'bool', nullable: false },
      next_run_at: { type: 'timestamptz', nullable: false },
      last_slot_at: { type: 'timestamptz', nullable: true },
      created_at: { type: 'timestamptz', nullable: false },
      updated_at: { type: 'timestamptz', nullable: false },
    },
    workflow_runs: {
      id: { type: 'uuid', nullable: false },
      kind: { type: 'workflow_run_kind', nullable: false },
      name: { type: 'text', nullable: false },
      workflow_name: { type: 'text', nullable: false },
      task_name: { type: 'text', nullable: true },
      status: { type: 'workflow_run_status', nullable: false },
      input: { type: 'jsonb', nullable: false },
      output: { type: 'jsonb', nullable: true },
      error: { type: 'jsonb', nullable: true },
      parent_run_id: { type: 'uuid', nullable: true },
      parent_node_name: { type: 'text', nullable: true },
      root_run_id: { type: 'uuid', nullable: false },
      tags: { type: 'jsonb', nullable: false },
      idempotency_key: { type: 'jsonb', nullable: true },
      version: { type: 'int4', nullable: false },
      created_at: { type: 'timestamptz', nullable: false },
      updated_at: { type: 'timestamptz', nullable: false },
    },
    workflow_nodes: {
      run_id: { type: 'uuid', nullable: false },
      name: { type: 'text', nullable: false },
      kind: { type: 'workflow_node_kind', nullable: false },
      status: { type: 'workflow_node_status', nullable: false },
      input: { type: 'jsonb', nullable: true },
      output: { type: 'jsonb', nullable: true },
      error: { type: 'jsonb', nullable: true },
      selected_case: { type: 'text', nullable: true },
      version: { type: 'int4', nullable: false },
      created_at: { type: 'timestamptz', nullable: false },
      updated_at: { type: 'timestamptz', nullable: false },
    },
    workflow_attempts: {
      id: { type: 'uuid', nullable: false },
      run_id: { type: 'uuid', nullable: false },
      node_name: { type: 'text', nullable: false },
      child_key: { type: 'text', nullable: false },
      status: { type: 'workflow_attempt_status', nullable: false },
      worker_id: { type: 'text', nullable: true },
      lease_token: { type: 'text', nullable: true },
      attempt_number: { type: 'int4', nullable: false },
      input: { type: 'jsonb', nullable: false },
      idempotency_key: { type: 'jsonb', nullable: true },
      output: { type: 'jsonb', nullable: true },
      error: { type: 'jsonb', nullable: true },
      dispatched_at: { type: 'timestamptz', nullable: false },
      heartbeat_at: { type: 'timestamptz', nullable: true },
      completed_at: { type: 'timestamptz', nullable: true },
    },
    workflow_node_children: {
      run_id: { type: 'uuid', nullable: false },
      node_name: { type: 'text', nullable: false },
      child_key: { type: 'text', nullable: false },
      kind: { type: 'workflow_node_child_kind', nullable: false },
      status: { type: 'workflow_node_status', nullable: false },
      ordinal: { type: 'int4', nullable: false },
      item_key: { type: 'text', nullable: true },
      item: { type: 'jsonb', nullable: true },
      input: { type: 'jsonb', nullable: true },
      output: { type: 'jsonb', nullable: true },
      error: { type: 'jsonb', nullable: true },
      child_run_id: { type: 'uuid', nullable: true },
      current_attempt_id: { type: 'uuid', nullable: true },
      attempt_count: { type: 'int4', nullable: false },
      version: { type: 'int4', nullable: false },
      created_at: { type: 'timestamptz', nullable: false },
      updated_at: { type: 'timestamptz', nullable: false },
    },
    workflow_run_leases: {
      run_id: { type: 'uuid', nullable: false },
      lease_token: { type: 'text', nullable: false },
      version: { type: 'int4', nullable: false },
      expires_at: { type: 'timestamptz', nullable: false },
    },
    workflow_run_events: {
      id: { type: 'int8', nullable: false },
      run_id: { type: 'uuid', nullable: false },
      root_run_id: { type: 'uuid', nullable: false },
      kind: { type: 'text', nullable: false },
      status: { type: 'text', nullable: false },
      node_name: { type: 'text', nullable: true },
      child_key: { type: 'text', nullable: true },
      attempt_id: { type: 'uuid', nullable: true },
      attempt_number: { type: 'int4', nullable: true },
      error: { type: 'jsonb', nullable: true },
      created_at: { type: 'timestamptz', nullable: false },
    },
    workflow_commands: {
      id: { type: 'uuid', nullable: false },
      kind: { type: 'workflow_command_kind', nullable: false },
      run_id: { type: 'uuid', nullable: false },
      workflow_name: { type: 'text', nullable: true },
      task_name: { type: 'text', nullable: true },
      activity_name: { type: 'text', nullable: true },
      node_name: { type: 'text', nullable: true },
      attempt_id: { type: 'uuid', nullable: true },
      payload: { type: 'jsonb', nullable: false },
      run_at: { type: 'timestamptz', nullable: false },
      priority: { type: 'int4', nullable: false },
      lease_owner: { type: 'text', nullable: true },
      lease_token: { type: 'text', nullable: true },
      lease_expires_at: { type: 'timestamptz', nullable: true },
      delivery_count: { type: 'int4', nullable: false },
      last_error: { type: 'jsonb', nullable: true },
      dead_at: { type: 'timestamptz', nullable: true },
      reaped_at: { type: 'timestamptz', nullable: true },
      created_at: { type: 'timestamptz', nullable: false },
    },
  },
} as const
