export const WORKFLOW_POSTGRES_SCHEMA_VERSION = 3
export const WORKFLOW_POSTGRES_SCHEMA_MANIFEST = {
  version: WORKFLOW_POSTGRES_SCHEMA_VERSION,
  enums: [
    'workflow_run_kind',
    'workflow_node_kind',
    'workflow_run_status',
    'workflow_node_status',
    'workflow_attempt_status',
    'workflow_command_kind',
  ],
  enumValues: {
    workflow_run_kind: ['workflow', 'task'],
    workflow_node_kind: [
      'activity',
      'task',
      'workflow',
      'branch',
      'parallel',
      'mapTask',
      'mapWorkflow',
    ],
    workflow_run_status: [
      'queued',
      'running',
      'waiting',
      'cancelling',
      'cancelled',
      'failed',
      'completed',
    ],
    workflow_node_status: [
      'pending',
      'running',
      'waiting',
      'cancelling',
      'cancelled',
      'failed',
      'completed',
    ],
    workflow_attempt_status: [
      'started',
      'completed',
      'failed',
      'timedOut',
      'cancelled',
    ],
    workflow_command_kind: ['continue', 'activity', 'task'],
  },
  tables: [
    'workflow_schema_version',
    'workflow_runs',
    'workflow_nodes',
    'workflow_attempts',
    'workflow_child_links',
    'workflow_map_item_sets',
    'workflow_map_items',
    'workflow_run_leases',
    'workflow_commands',
  ],
  constraints: [
    'workflow_schema_version_pkey',
    'workflow_schema_version_singleton_chk',
    'workflow_runs_pkey',
    'workflow_nodes_pkey',
    'workflow_attempts_pkey',
    'workflow_attempts_identity_key_key',
    'workflow_child_links_pkey',
    'workflow_map_item_sets_pkey',
    'workflow_map_items_pkey',
    'workflow_map_items_identity_key_key',
    'workflow_run_leases_pkey',
    'workflow_commands_pkey',
    'workflow_runs_parent_run_fk',
    'workflow_runs_root_run_fk',
    'workflow_runs_parent_node_fk',
    'workflow_nodes_run_fk',
    'workflow_nodes_current_attempt_fk',
    'workflow_attempts_node_fk',
    'workflow_child_links_parent_node_fk',
    'workflow_child_links_child_run_fk',
    'workflow_map_item_sets_node_fk',
    'workflow_map_items_set_fk',
    'workflow_map_items_child_run_fk',
    'workflow_map_items_attempt_fk',
    'workflow_run_leases_run_fk',
    'workflow_commands_run_fk',
  ],
  indexes: [
    'workflow_runs_idempotency_idx',
    'workflow_runs_parent_idx',
    'workflow_runs_root_idx',
    'workflow_runs_input_gin_idx',
    'workflow_runs_tags_gin_idx',
    'workflow_attempts_node_idx',
    'workflow_child_links_parent_node_idx',
    'workflow_commands_run_idx',
    'workflow_commands_claim_idx',
    'workflow_commands_continue_dedup_idx',
  ],
  constraintDefinitions: {
    workflow_attempts_identity_key_key: {
      table: 'workflow_attempts',
      type: 'u',
      columns: ['identity_key'],
    },
    workflow_map_items_identity_key_key: {
      table: 'workflow_map_items',
      type: 'u',
      columns: ['identity_key'],
    },
    workflow_commands_run_fk: {
      table: 'workflow_commands',
      type: 'f',
      columns: ['run_id'],
    },
  },
  indexDefinitions: {
    workflow_runs_idempotency_idx: {
      table: 'workflow_runs',
      unique: true,
      columns: ['idempotency_key'],
      predicate: 'idempotency_key IS NOT NULL',
    },
    workflow_runs_parent_idx: {
      table: 'workflow_runs',
      unique: false,
      columns: ['parent_run_id'],
      predicate: 'parent_run_id IS NOT NULL',
    },
    workflow_runs_root_idx: {
      table: 'workflow_runs',
      unique: false,
      columns: ['root_run_id'],
    },
    workflow_runs_input_gin_idx: {
      table: 'workflow_runs',
      unique: false,
      columns: ['input'],
    },
    workflow_runs_tags_gin_idx: {
      table: 'workflow_runs',
      unique: false,
      columns: ['tags'],
    },
    workflow_commands_claim_idx: {
      table: 'workflow_commands',
      unique: false,
      columns: ['kind', 'priority', 'run_at', 'created_at', 'id'],
      directions: ['ASC', 'DESC', 'ASC', 'ASC', 'ASC'],
    },
    workflow_commands_run_idx: {
      table: 'workflow_commands',
      unique: false,
      columns: ['run_id'],
    },
    workflow_commands_continue_dedup_idx: {
      table: 'workflow_commands',
      unique: true,
      columns: ['run_id'],
      predicate:
        "kind = 'continue'::workflow_command_kind AND lease_token IS NULL",
    },
    workflow_attempts_node_idx: {
      table: 'workflow_attempts',
      unique: false,
      columns: ['run_id', 'node_name'],
    },
    workflow_child_links_parent_node_idx: {
      table: 'workflow_child_links',
      unique: false,
      columns: ['parent_run_id', 'parent_node_name'],
    },
  },
  columns: {
    workflow_schema_version: {
      id: { type: 'int4', nullable: false },
      version: { type: 'int4', nullable: false },
      installed_at: { type: 'timestamptz', nullable: false },
    },
    workflow_runs: {
      id: { type: 'uuid', nullable: false },
      kind: { type: 'workflow_run_kind', nullable: false },
      name: { type: 'text', nullable: false },
      workflow_name: { type: 'text', nullable: false },
      task_name: { type: 'text', nullable: true },
      status: { type: 'workflow_run_status', nullable: false },
      input: { type: 'jsonb', nullable: false },
      output: { type: 'jsonb', nullable: true },
      error: { type: 'jsonb', nullable: true },
      parent_run_id: { type: 'uuid', nullable: true },
      parent_node_name: { type: 'text', nullable: true },
      root_run_id: { type: 'uuid', nullable: false },
      tags: { type: 'jsonb', nullable: false },
      idempotency_key: { type: 'jsonb', nullable: true },
      version: { type: 'int4', nullable: false },
      created_at: { type: 'timestamptz', nullable: false },
      updated_at: { type: 'timestamptz', nullable: false },
    },
    workflow_nodes: {
      run_id: { type: 'uuid', nullable: false },
      name: { type: 'text', nullable: false },
      kind: { type: 'workflow_node_kind', nullable: false },
      status: { type: 'workflow_node_status', nullable: false },
      input: { type: 'jsonb', nullable: true },
      output: { type: 'jsonb', nullable: true },
      error: { type: 'jsonb', nullable: true },
      selected_case: { type: 'text', nullable: true },
      current_attempt_id: { type: 'uuid', nullable: true },
      next_attempt_at: { type: 'timestamptz', nullable: true },
      attempt_count: { type: 'int4', nullable: false },
      version: { type: 'int4', nullable: false },
      created_at: { type: 'timestamptz', nullable: false },
      updated_at: { type: 'timestamptz', nullable: false },
    },
    workflow_attempts: {
      id: { type: 'uuid', nullable: false },
      run_id: { type: 'uuid', nullable: false },
      node_name: { type: 'text', nullable: false },
      identity_key: { type: 'text', nullable: true },
      identity: { type: 'jsonb', nullable: true },
      status: { type: 'workflow_attempt_status', nullable: false },
      worker_id: { type: 'text', nullable: true },
      lease_token: { type: 'text', nullable: true },
      attempt_number: { type: 'int4', nullable: false },
      input: { type: 'jsonb', nullable: false },
      idempotency_key: { type: 'jsonb', nullable: true },
      output: { type: 'jsonb', nullable: true },
      error: { type: 'jsonb', nullable: true },
      dispatched_at: { type: 'timestamptz', nullable: false },
      heartbeat_at: { type: 'timestamptz', nullable: true },
      completed_at: { type: 'timestamptz', nullable: true },
    },
    workflow_child_links: {
      identity_key: { type: 'text', nullable: false },
      identity: { type: 'jsonb', nullable: false },
      parent_run_id: { type: 'uuid', nullable: false },
      parent_node_name: { type: 'text', nullable: false },
      child_run_id: { type: 'uuid', nullable: false },
      child_kind: { type: 'workflow_run_kind', nullable: false },
      child_name: { type: 'text', nullable: false },
      workflow_name: { type: 'text', nullable: false },
      task_name: { type: 'text', nullable: true },
      case_key: { type: 'text', nullable: true },
      member_key: { type: 'text', nullable: true },
      item_index: { type: 'int4', nullable: true },
      item_key: { type: 'text', nullable: true },
    },
    workflow_map_item_sets: {
      run_id: { type: 'uuid', nullable: false },
      node_name: { type: 'text', nullable: false },
      keys: { type: 'jsonb', nullable: false },
    },
    workflow_map_items: {
      run_id: { type: 'uuid', nullable: false },
      node_name: { type: 'text', nullable: false },
      item_index: { type: 'int4', nullable: false },
      identity_key: { type: 'text', nullable: false },
      identity: { type: 'jsonb', nullable: false },
      item_key: { type: 'text', nullable: true },
      item: { type: 'jsonb', nullable: false },
      status: { type: 'workflow_node_status', nullable: false },
      output: { type: 'jsonb', nullable: true },
      error: { type: 'jsonb', nullable: true },
      child_run_id: { type: 'uuid', nullable: true },
      attempt_id: { type: 'uuid', nullable: true },
    },
    workflow_run_leases: {
      run_id: { type: 'uuid', nullable: false },
      lease_token: { type: 'text', nullable: false },
      version: { type: 'int4', nullable: false },
      expires_at: { type: 'timestamptz', nullable: false },
    },
    workflow_commands: {
      id: { type: 'uuid', nullable: false },
      kind: { type: 'workflow_command_kind', nullable: false },
      run_id: { type: 'uuid', nullable: false },
      workflow_name: { type: 'text', nullable: true },
      task_name: { type: 'text', nullable: true },
      activity_name: { type: 'text', nullable: true },
      node_name: { type: 'text', nullable: true },
      attempt_id: { type: 'uuid', nullable: true },
      payload: { type: 'jsonb', nullable: false },
      run_at: { type: 'timestamptz', nullable: false },
      priority: { type: 'int4', nullable: false },
      lease_owner: { type: 'text', nullable: true },
      lease_token: { type: 'text', nullable: true },
      lease_expires_at: { type: 'timestamptz', nullable: true },
      delivery_count: { type: 'int4', nullable: false },
      last_error: { type: 'jsonb', nullable: true },
      dead_at: { type: 'timestamptz', nullable: true },
      created_at: { type: 'timestamptz', nullable: false },
    },
  },
} as const
