/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NeemataProxy {
  constructor(apps: Record<string, ApplicationConfig>, options?: GatewayOptions | undefined | null)
  run(): void
  shutdown(): void
}

export interface ApplicationConfig {
  upstreams: Array<string>
  sni?: string
  enableTls?: boolean
}

export interface GatewayOptions {
  listen?: string
  threads?: number
  healthCheckIntervalSecs?: number
}
