name: Build and publish

on:
  release:
    types: [published]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install -g pnpm
      - name: Log in to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.npm_token}}" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
      - name: Publish
        run: |
          pnpm install
          bun run build
          pnpm version ${{ github.event.release.tag_name }} -ws --no-commit-hooks --no-git-tag-version --silent || true
          pnpm publish --filter "*" --access public --no-git-checks
        
